version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "deps(npm)"
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:15"
      timezone: "UTC"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps(actions)"

